apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: {{ .Values.services.api-gateway.service.port }}
    targetPort: 8080
    nodePort: {{ .Values.services.api-gateway.service.nodePort }}
  type: {{ .Values.services.api-gateway.service.type }}